---
- set_fact:
    openshift_installer_release: "4.1.3"
    openshift_installer_release_type: "linux"

- name: Setting openshift-installer facts for MacOS
  set_fact:
    openshift_installer_release_type: "darwin"
  when: ansible_os_family == "Darwin"

- set_fact:
    openshift_installer_release_url: "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-install-{{ openshift_installer_release_type }}-{{ openshift_installer_release }}.tar.gz"

- name: get installer
  get_url:
    url: "{{ openshift_installer_release_url }}"
    dest: "{{ playbook_dir }}/openshift-install.tar.gz"

- name: untar installer
  unarchive:
    src: openshift-install.tar.gz
    creates: "{{ playbook_dir }}/openshift-install"
    exclude: ["README.md"]
    dest: "{{ playbook_dir }}"
