---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: migration-registry
  name: migration-registry
  namespace: migration-registry
spec:
  ports:
  - name: 5000-tcp
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: migration-registry
    deploymentconfig: migration-registry
status:
  loadBalancer: {}
